"""Initial schema with all tables

Revision ID: 9c4271ac0657
Revises: 
Create Date: 2026-01-29 23:22:12.391802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4271ac0657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aois',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.Column('size_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sentinel_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('aoi_id', sa.Integer(), nullable=False),
    sa.Column('acquisition_dt', sa.DateTime(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cloud_cover >= 0 AND cloud_cover <= 100', name='check_cloud_cover_range'),
    sa.ForeignKeyConstraint(['aoi_id'], ['aois.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('download_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('download_start', sa.DateTime(), nullable=True),
    sa.Column('download_end', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'downloaded', 'failed', 'processing', 'processed')", name='check_status_valid'),
    sa.ForeignKeyConstraint(['product_id'], ['sentinel_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('snow_masks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ndsi_threshold', sa.Float(), nullable=False),
    sa.Column('snow_pixels', sa.Integer(), nullable=False),
    sa.Column('total_pixels', sa.Integer(), nullable=False),
    sa.Column('snow_pct', sa.Float(), nullable=False),
    sa.Column('mask_path', sa.Text(), nullable=True),
    sa.Column('processing_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['sentinel_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'ndsi_threshold', name='unique_product_threshold')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snow_masks')
    op.drop_table('download_status')
    op.drop_table('sentinel_products')
    op.drop_table('aois')
    # ### end Alembic commands ###
